"""added many-to many relationship

Revision ID: 14afbd7be8c7
Revises: e341c9fc92e8
Create Date: 2023-09-04 04:19:39.426466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14afbd7be8c7'
down_revision: Union[str, None] = 'e341c9fc92e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
